{
 "title": "PV Station",
 "description": "PV Installation",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "InverterWest", "query": "[YOUR INVERTER SERIAL2]" },
   { "name": "InverterEast", "query": "[YOUR INVERTER SERIAL1]" },
   {
    "name": "telegraf_all",
    "query": "//Bucketfilter to filter only buckets beginning with name telegraf..\r\nbucketfilter = /telegraf.*/\r\n\r\nbuckets()\r\n  |> filter(fn: (r) => r.name =~ bucketfilter)\r\n  //convert retentionperiod from nanosecond to days\r\n  |> map(fn: (r) => ({r with \r\n    retentionPeriodinDays: r.retentionPeriod / 86400000000000}) \r\n  )\r\n  //replace retentionpolicy infinity with a high number in NS\r\n  |> map(fn: (r) => ({r with\r\n    retentionPeriod: if r.retentionPeriod == 0 then 999999999999999999\r\n    else r.retentionPeriod})\r\n  )\r\n  //calculate the duration from \"to\" and \"from\" timespan and convert it to nanosecond\r\n  |> map(fn: (r) => ({r with \r\n    DashboardDurationinNS: (${__to} - ${__from}) * 1000000})\r\n  )\r\n  |> filter(fn: (r) => \r\n    r.DashboardDurationinNS <= r.retentionPeriod and\r\n    r.retentionPeriod >= uint(v: now()) - uint(v: ${__from} * 1000000)\r\n  )\r\n  |> sort(columns: [\"retentionPeriod\"], desc: false)\r\n  |> limit(n: 1)\r\n  |> keep(columns: [\"name\"]) //remove all fields except for \"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Power Now",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${telegraf_all}\")\n  |> range(start: -1d)\n  |> filter(fn: (r) => r._measurement =~ /mqtt*/)\n  |> filter(fn: (r) => r._field == \"power\")\n  |> filter(fn: (r) => r.channel == \"0\")\n  |> truncateTimeColumn(unit: 2m)\n  |> hourSelection(start: 4, stop: 22)\n  \n\n"
    }
   ]
  },
  {
   "title": "Yield Total Today",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${telegraf_all}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /mqtt*/)\n  |> filter(fn: (r) => r._field == \"yieldday\")\n  |> filter(fn: (r) => r.channel == \"0\")\n  |> truncateTimeColumn(unit: 20m)\n  |> last()\n\n"
    }
   ]
  },
  {
   "title": "Yield Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${telegraf_all}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /mqtt*/)\n  |> filter(fn: (r) => r._field == \"yieldtotal\")\n  |> filter(fn: (r) => r.channel == \"0\")\n  |> truncateTimeColumn(unit: 20m)\n  |> last()\n\n"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${telegraf_all}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /mqtt*/)\n  |> filter(fn: (r) => r._field == \"power\")\n  |> filter(fn: (r) => r.channel == \"0\")\n  |> truncateTimeColumn(unit: 2m)\n\n"
    }
   ]
  },
  {
   "title": "Temperature-East",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${telegraf_all}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /mqtt*/)\n  |> filter(fn: (r) => r.channel == \"0\" and r.serial == \"${InverterEast}\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Temperature-West",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"${telegraf_all}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /mqtt*/)\n  |> filter(fn: (r) => r.channel == \"0\" and r.serial == \"${InverterWest}\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Yield per day",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"${telegraf_all}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement =~ /mqtt*/)\n  |> filter(fn: (r) => r._field == \"yieldday\")\n  |> filter(fn: (r) => r.channel == \"0\")\n  |> truncateTimeColumn(unit: 1d)\n\n\n\n\n"
    }
   ]
  }
 ]
}